# Generated by Django 4.2.6 on 2023-10-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dolist',
            new_name='Task',
        ),
    ]
