# Generated by Django 4.2.6 on 2023-11-01 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dolist", "0003_task_manager"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="manager",
            new_name="manage",
        ),
    ]
